name: Publish java libs
on:
  workflow_call:
    inputs:
      version:
        description: 'Version'
        required: false
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-java-docker-libs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Set up the JDK used to run Gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Build java
        run: |
          if [ "${{ inputs.version }}" != '' ]; then
            NEW_VERSION=${{ inputs.version }}
          elif [[ ${{ github.event_name }} == 'pull_request' ]]; then
            NEW_VERSION=0.1.pr-${{ github.event.number }}.${{ github.run_number }}-${{ github.run_attempt }}
          else
            NEW_VERSION=0.1.$(echo ${{ github.ref }} | cut -d'/' -f3).${{ github.sha }}
          fi
          echo "New version: ${NEW_VERSION}"
          echo "Github username: ${GITHUB_ACTOR}"
          ./gradlew -Pversion=${NEW_VERSION} build

      - name: Publish package
        run: |
          if [ "${{ inputs.version }}" != '' ]; then
            NEW_VERSION=${{ inputs.version }}
          elif [[ ${{ github.event_name }} == 'pull_request' ]]; then
            NEW_VERSION=0.1.pr-${{ github.event.number }}.${{ github.run_number }}-${{ github.run_attempt }}
          else
            NEW_VERSION=0.1.$(echo ${{ github.ref }} | cut -d'/' -f3).${{ github.sha }}
          fi
          echo "New version: ${NEW_VERSION}"
          echo "Github username: ${GITHUB_ACTOR}"
          ./gradlew -Pversion=${NEW_VERSION} publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}